### ISSUE TITLE
Problem of dataset

### ISSUE THREAD

**Issue by yoletPig** [tvelovraf/Pigs-segmentation-and-tracking#3]
I am sorry about that I can't find the train dataset and annotation files in this repo.Could you please share your dataset with us？

**Comment by tvelovraf** [comment]
Hi @yoletPig
Sorry for such a long responce time

The pure train dataset is available there: https://drive.google.com/file/d/1Al-vfYyNfrXaSj0MwHj9nSkMqPuOkjAC/view
We used every 10th shot from every video to compose our dataset.
Unfortunately, there is no annotation files left.

**Comment by yoletPig** [comment]
Thank you so much!Best Wishes!
&nbsp;


1248619300
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rafael ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 晚上8:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tvelovraf/Pigs-segmentation-and-tracking] Problem of dataset (Issue #3)





 
Hi @yoletPig
 Sorry for such a long responce time
 
The pure train dataset is available there: https://drive.google.com/file/d/1Al-vfYyNfrXaSj0MwHj9nSkMqPuOkjAC/view
 We used every 10th shot from every video to compose our dataset.
 Unfortunately, there is no annotation files left.

**Comment by tvelovraf** [comment]
Hi @yoletPig
Sorry for such a long responce time

The pure train dataset data is available there: https://drive.google.com/file/d/1Al-vfYyNfrXaSj0MwHj9nSkMqPuOkjAC/view
We used every 10th shot from every video to compose our dataset.
Unfortunately, there is no annotation files left.

You can make inference using our pretrained weights and use get annotaitions from that.

**Comment by tvelovraf** [comment]
Hi @yoletPig
Sorry for such a long responce time

The pure train dataset data is available there: https://drive.google.com/file/d/1Al-vfYyNfrXaSj0MwHj9nSkMqPuOkjAC/view
We used every 10th shot from every video to compose our dataset.
Unfortunately, there is no annotation files left.

You can make inference using our pre-trained weights and use the resulting annotations.
If obtained annotations are not perfect, then you can manualy refine them.

Some annotaition details (used tool and annotation files configuration) are mentioned there
https://github.com/tvelovraf/Pigs-segmentation-and-tracking/issues/2#issuecomment-1336399752

**Comment by yoletPig** [comment]
I also want to do that.Maybe it will work perfectly.&nbsp;


1248619300
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rafael ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 晚上9:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tvelovraf/Pigs-segmentation-and-tracking] Problem of dataset (Issue #3)





 
Hi @yoletPig
 Sorry for such a long responce time
 
The pure train dataset data is available there: https://drive.google.com/file/d/1Al-vfYyNfrXaSj0MwHj9nSkMqPuOkjAC/view
 We used every 10th shot from every video to compose our dataset.
 Unfortunately, there is no annotation files left.
 
You can make inference using our pre-trained weights and use the resulting annotations.
 If obtained annotations are not perfect, then you can manualy refine them.
 
Some annotaition details (used tool and annotation files configuration) are mentioned there
 #2 (comment)
